# Reservoir Simulation configuration.
path: "/home/hygorcosta/Documentos/Phd/PyMEX/reservoir_tpl"
template: 'Diego1_2v.tpl'
prices: [25, 15, 5, 0.09]
nb_cycles: 2
nb_prod: 2
nb_inj: 1
time_concession: 3600
max_rate_prod: 30
max_rate_inj: 44
max_plat_prod: 300
max_plat_inj: 400
type_opera: 1
type_time: 0
