# Reservoir Simulation configuration.
path: "/home/hygorcosta/Documentos/Phd/PlotPymex/PyMEX/reservoir_tpl"
run_folder: 'spe10/wav_1'
ups_level: 0
template:
  - 'mxspe010_wav_1.dat'
  # - 'spe10_wav_3.tpl'
  # - 'spe10_wav_2.tpl'
  # - 'spe10_wav_1.tpl'
  # - 'mxspe10.tpl'
original: 'mxspe10.tpl'
prices: [48, 0.15, 0.05, 0]
nb_cycles: 3
nb_prod: 1
nb_inj: 1
time_concession: 7300
max_rate_prod: 500
max_rate_inj: 500
max_plat_prod: False
max_plat_inj: False
type_opera: 1
type_time: 0
min_inj: 0
min_prod: 0
